app.py
""" Imports """
import os
from flask import Flask
from dotenv import load_dotenv
from extentions.database import mongo
from routes.main import home
from routes.test import testRoutes
from routes.post import postRoutes
from routes.mails import mailsRoutes
from routes.phones import phoneRoutes

# Carrega as variáveis de ambiente armazenadas no arquivo .env
load_dotenv()
# Acessa a variável de ambiente MONGO_URI
MONGO_URI = os.getenv("MONGO_URI")

# Inicia a aplicação
app = Flask(__name__)
# Carrega o caminho do banco de dados armazenado na variável MONGO_URI configurada no arquivo .env
app.config["MONGO_URI"] = MONGO_URI
# Gerar chaves automáticas com 48 caracteres
app.config["SECRET_KEY"] = os.urandom(48)
# Inicializa o banco de dados
mongo.init_app(app)
# Blueprint - Organiza as rotas por grupos
app.register_blueprint(home)
app.register_blueprint(testRoutes)
app.register_blueprint(postRoutes)
app.register_blueprint(mailsRoutes)
app.register_blueprint(phoneRoutes)


if __name__ == '__main__':
    app.run(debug=True)

routes/mails.py
""" Imports """
from flask import Blueprint, render_template

mailsRoutes = Blueprint("mailsRoutes", __name__)


@mailsRoutes.route("/mails/insert")
def insert_mail():
    """ Inserir e-mails """
    return render_template("mails/insert.html")

@mailsRoutes.route("/mails/list")
def list_mail():
    """ Listar e-mails """
    return render_template("mails/list.html")

routes/main.py
""" Imports """
from flask import Blueprint, render_template

home = Blueprint("home", __name__)


@home.route("/")
def home_page():
    """ Route Home """
    return render_template("/index.html")

routes/phones.py
""" Imports """
from flask import Blueprint, render_template

phoneRoutes = Blueprint("phoneRoutes", __name__)


@phoneRoutes.route("/phones/insert")
def insert_phone():
    """ Inserir ramais/whatsapp """
    return render_template("phones/insert.html")

@phoneRoutes.route("/phones/list")
def list_phone():
    """ Listar ramais/whatsapp """
    return render_template("phones/list.html")

routes/post.py
""" Imports """
import base64
import datetime
from pymongo import TEXT
from bson import ObjectId
from flask import Blueprint, render_template, request, flash, redirect, url_for
from slugify import slugify
from extentions.database import mongo


postRoutes = Blueprint("postRoutes", __name__)


@postRoutes.route("/solutions/insert", methods=["GET", "POST"])
def insert_solution():
    """ Insert Post """

    if request.method == "GET":
        return render_template("posts/insert.html")
    else:
        title = request.form.get('title')
        slug = slugify(title)
        author = request.form.get('author')
        content = request.form.get('content')

        # Calculando o hash da imagem
        image = request.files['image']
        image_data = image.read()
        image_base64 = base64.b64encode(image_data).decode('utf-8')

        # Criando novo post
        mongo.cx.cmtools.posts.insert_one(
            {
                "title": title,
                "slug": slug,
                "date": datetime.datetime.now(),
                "author": author,
                "content": content,
                "image_base64": image_base64
            }
        )

        flash("Post inserido com sucesso!")
        return redirect(url_for("postRoutes.list_all_solutions"))


# @postRoutes.route("/solutions/list")
# def list_all_solutions():
#     """ Listar Post """
#     posts_cursor = mongo.cx.cmtools.posts.find()
#     posts = list(posts_cursor)
#     return render_template("posts/list.html", posts=posts)

@postRoutes.route("/solutions/list", methods=["GET"])
def list_all_solutions():
    """ Listar Post """
    # Crie um índice de texto na coleção 'posts' nos campos 'title' e 'content'
    mongo.cx.cmtools.posts.create_index([("title", TEXT), ("content", TEXT)])

    query = request.args.get(
        'query')  # Obter o parâmetro de consulta 'query' da URL
    if query:
        # Se houver uma consulta, encontrar posts que correspondam à consulta
        posts_cursor = mongo.cx.cmtools.posts.find(
            {"$text": {"$search": query}})
    else:
        # Caso contrário, retornar todos os posts
        posts_cursor = mongo.cx.cmtools.posts.find()

    posts = list(posts_cursor)
    return render_template("posts/list.html", posts=posts)


@postRoutes.route("/solutions/<string:slug>")
def view_solution(slug):
    """ Encontra o post corresponde ao slug """
    posts_cursor = mongo.cx.cmtools.posts.find()  # Buscar os posts novamente
    posts = list(posts_cursor)

    post_data = next((post for post in posts if post['slug'] == slug), None)
    if post_data:
        return render_template('posts/view.html', post=post_data)
    else:
        return 'Post not found', 404


@postRoutes.route("/solutions/delete/<string:solution_id>")
def delete_solution(solution_id):
    """ Delete post """
    result = mongo.cx.cmtools.posts.delete_one({"_id": ObjectId(solution_id)})
    if result.deleted_count == 1:
        flash("Solução excluida com sucesso!")
    else:
        flash("ID não encontrado")
    return redirect(url_for("postRoutes.list_all_solutions"))


@postRoutes.route("/solutions/edit/<string:solution_id>", methods=["GET", "POST"])
def edit_solution(solution_id):
    """ Editar post """
    if request.method == "GET":
        post_data = mongo.cx.cmtools.posts.find_one(
            {"_id": ObjectId(solution_id)})
        return render_template("posts/edit.html", post=post_data)
    else:
        # Obter dados do formulário de edição
        title = request.form.get('title')
        author = request.form.get('author')
        image_base64 = request.form.get('image_base64')
        content = request.form.get('content')

        # Atualizar os dados do post
        result = mongo.cx.cmtools.posts.update_one(
            {"_id": ObjectId(solution_id)},
            {"$set": {"title": title, "author": author,
                      "content": content, "image_base64": image_base64}}
        )

        if result.modified_count == 1:
            flash("Post atualizado com sucesso!")
        else:
            flash("Falha ao atualizar o post.")

        return redirect(url_for("postRoutes.list_all_solutions"))

routes/test.py
""" Imports """
from flask import Blueprint
from extentions.database import mongo

testRoutes = Blueprint("testRoutes", __name__)


@testRoutes.route('/test/testMails')
def test_mails():
    """ Teste Conexão """
    collection = mongo.cx.cmtools.mails
    collection.insert_one({
        'email': 'suporte@suporte.com.br',
        'password': "senha123"
    })
    return '<h1>E-mail adicionado no banco!</h1>'


@testRoutes.route('/test/testPost')
def test_post():
    """ Teste Conexão """
    collection = mongo.cx.cmtools.posts
    collection.insert_one({
        'title': 'Post teste',
        'slug': "post-teste",
        'author': "Administrador",
        'content': "Adicionando um post teste!"
    })
    return '<h1>Post adicionado no banco!</h1>'


@testRoutes.route('/test/testPhone')
def test_phone():
    """ Teste Conexão """
    collection = mongo.cx.cmtools.phones
    collection.insert_one({
        'user': 'suporte@suporte.com.br',
        'phone': "48991736262",
        'whatsapp': "48991736262"
    })
    return '<h1>Telefone adicionado no banco!</h1>'

templates/index.html
{% extends "layout.html" %} 

{% block header %}
  <div>Página principal</div>
{% endblock %}

{% block content %}

<h1>Página Home!</h1>

{% endblock %}

templates/phones/insert.html
{% extends "layout.html" %}

{% block content %}
  <h1>Inserir Ramais/Whatsapp</h1>
{% endblock %}

templates/phones/list.html
{% extends "layout.html" %}

{% block content %}
  <h1>Listar phones</h1>
{% endblock %}

templates/posts/edit.html
{% extends "layout.html" %} 

{% block content %}
<div class="container mx-auto max-w-5xl p-6">
  <h1 class="pb-8 text-xl">Adicionar solução</h1>

  <form action="" method="post" enctype="multipart/form-data">
    <div class="border-b border-gray-900/10 pb-16 max-w-5xl mx-auto">
      <div class="grid grid-cols-1 gap-6">
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="title">Título do post</label>
          <input class="w-full border border-gray-300 rounded-xl py-4 px-6" type="text" id="title" name="title" required value="{{ post.title }}" />
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="author">Autor do post</label>
          <input class="w-full border border-gray-300 rounded-xl py-4 px-6" type="text" id="author" name="author" required value="{{ post.author }}" />
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="image">Inserir imagem</label>
          <div class="flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">            
            <div class="text-center">
              <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
              </svg>
              <input class="file:cursor-pointer cursor-pointer file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100" type="file" id="image" name="image" aria-describedby="file_input_help" value="{{ post.image_base64 }}" />
              <p class="text-xs leading-5 text-gray-600">PNG, JPG</p>
            </div>
          </div>
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="content">Conteúdo</label>
          <div id="editor" class="w-full text-base font-medium border border-gray-300 rounded-b-xl py-4 px-6">{{post.content | safe}}</div>
          <input type="hidden" id="content" name="content" />
        </div>
      </div>
    </div>
    <div class="max-w-5xl mx-auto mt-6 flex items-center justify-end gap-x-4">
      <button type="button" class="leading-6 text-gray-900 border border-gray-300 hover:border-indigo-500 hover:text-indigo-500 transition duration-500 rounded-xl px-6 py-4 tracking-wide">Cancelar</button>
      <button type="submit" class="rounded-xl px-6 py-4 tracking-wide bg-indigo-600 text-white hover:bg-indigo-500 transition duration-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" value="Save">Salvar</button>
    </div>
  </form>
</div>
{% endblock %}

templates/posts/insert.html
{% extends "layout.html" %} 

{% block content %}
<div class="container mx-auto max-w-5xl p-4">
  <h1 class="pb-8 text-xl">Adicionar solução</h1>

  <form action="{{ url_for('postRoutes.insert_solution') }}" method="post" enctype="multipart/form-data">
    <div class="border-b border-gray-900/10 pb-16 max-w-5xl mx-auto">
      <div class="grid grid-cols-1 gap-6">
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="title">Título do post</label>
          <input class="w-full border border-gray-300 rounded-xl py-4 px-6" type="text" id="title" name="title" required />
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="author">Autor do post</label>
          <input class="w-full border border-gray-300 rounded-xl py-4 px-6" type="text" id="author" name="author" required />
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="image">Inserir imagem</label>
          <div class="flex items-center justify-center w-full">
            <label for="dropzone-file" class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
              <div class="flex flex-col items-center justify-center pt-5 pb-6">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8 mb-3 text-gray-500 dark:text-gray-400">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 16.5V9.75m0 0 3 3m-3-3-3 3M6.75 19.5a4.5 4.5 0 0 1-1.41-8.775 5.25 5.25 0 0 1 10.233-2.33 3 3 0 0 1 3.758 3.848A3.752 3.752 0 0 1 18 19.5H6.75Z" />
                </svg>                
                <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold">Clique para adicionar uma imagem</p>
                <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG or GIF</p>
              </div>
              <input id="dropzone-file" type="file" class="hidden" />
            </label>
        </div> 
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="content">Conteúdo</label>
          <div id="editor" class="w-full text-base font-medium border border-gray-300 rounded-b-xl py-4 px-6"></div>
          <input type="hidden" id="content" name="content" />
        </div>
      </div>
    </div>
    <div class="max-w-5xl mx-auto mt-6 flex items-center justify-end gap-x-4">
      <button type="button" class="leading-6 text-gray-900 border border-gray-300 hover:border-indigo-500 hover:text-indigo-500 transition duration-500 rounded-xl px-6 py-4 tracking-wide">Cancelar</button>
      <button type="submit" class="rounded-xl px-6 py-4 tracking-wide bg-indigo-600 text-white hover:bg-indigo-500 transition duration-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Salvar</button>
    </div>
  </form>
</div>
{% endblock %}

templates/posts/insert_post.html
{% extends "layout.html" %} 

{% block header %}
  <a href="/" class="flex hover:text-indigo-500 group transition duration-500">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-500 mr-2 group-hover:text-indigo-500 transition duration-500">
      <path stroke-linecap="round" stroke-linejoin="round" d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3" />
    </svg>
    Voltar
  </a>
{% endblock %}

{% block content %}
<div class="container mx-auto max-w-5xl p-6">
  <h1 class="pb-8 text-xl">Adicionar solução</h1>

  <form action="{{ url_for('postRoutes.insert_post') }}" method="post" enctype="multipart/form-data">
    <div class="border-b border-gray-900/10 pb-16 max-w-5xl mx-auto">
      <div class="grid grid-cols-1 gap-6">
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="title">Título do post</label>
          <input class="w-full border border-gray-300 rounded-xl py-4 px-6" type="text" id="title" name="title" required />
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="author">Autor do post</label>
          <input class="w-full border border-gray-300 rounded-xl py-4 px-6" type="text" id="author" name="author" required />
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="image">Inserir imagem</label>
          <div class="flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">            
            <div class="text-center">
              <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z" clip-rule="evenodd" />
              </svg>
              <input class="file:cursor-pointer cursor-pointer file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100" type="file" id="image" name="image" aria-describedby="file_input_help" />
              <p class="text-xs leading-5 text-gray-600">PNG, JPG</p>
            </div>
          </div>
        </div>
        <div>
          <label class="block mb-2 text-sm font-medium text-gray-900" for="content">Conteúdo</label>
          <div id="editor" class="w-full text-base font-medium border border-gray-300 rounded-b-xl py-4 px-6"></div>
          <input type="hidden" id="content" name="content" />
        </div>
      </div>
    </div>
    <div class="max-w-5xl mx-auto mt-6 flex items-center justify-end gap-x-4">
      <button type="button" class="leading-6 text-gray-900 border border-gray-300 hover:border-indigo-500 hover:text-indigo-500 transition duration-500 rounded-xl px-6 py-4 tracking-wide">Cancelar</button>
      <button type="submit" class="rounded-xl px-6 py-4 tracking-wide bg-indigo-600 text-white hover:bg-indigo-500 transition duration-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Salvar</button>
    </div>
  </form>
</div>
{% endblock %}

templates/posts/list.html
{% extends "layout.html" %} 

{% block header %}
<a href="/posts/insert" class="flex items-center">
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-green-700 hover:text-green-500">
    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>        
  <span class="sr-only">Adicionar</span>
</a>
{% endblock %}

{% block content %}
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div id="alert-border-3" class="flex items-center p-4 mb-4 text-green-800 border-t-4 border-green-300 bg-green-50 dark:text-green-400 dark:bg-gray-800 dark:border-green-800" role="alert">
        <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
        </svg>
        {% for message in messages %}
          <div class="ms-3 text-sm font-medium">{{ message }}</div>
        {% endfor %}
        <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-green-50 text-green-500 rounded-lg focus:ring-2 focus:ring-green-400 p-1.5 hover:bg-green-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-gray-700"  data-dismiss-target="#alert-border-3" aria-label="Close">
          <span class="sr-only">Dismiss</span>
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
        </button>
      </div>
    {% endif %}
  {% endwith %}

  <form action="{{ url_for('postRoutes.list_all_solutions') }}" method="GET" class="relative block mb-6 max-w-screen-sm mx-auto">
    <label class="sr-only" for="search">Search</label>
    <span class="absolute inset-y-0 left-0 flex items-center pl-2">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-500">
        <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
      </svg>      
    </span>
    <input id="search" class="placeholder:text-gray-500 block bg-white w-full border border-gray-300 rounded-xl py-4 pl-9 pr-4 shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-indigo-500 focus:ring-1 sm:text-sm" placeholder="Pesquisar Soluções" type="text" name="query"/>
  </form>

  {% for post in posts %}
    <div class="bg-white p-8 mb-4 rounded-xl shadow hover:shadow-lg">
      <a class="flex justify-between items-center" href="{{ url_for('postRoutes.view_solution', slug=post['slug']) }}">
        <div>
          <h1 class="text-2xl font-semibold">{{ post.title }}</h1>
          <p class="font-light text-gray-400 py-4">{{ post.author }}</p>
          <div class="line-clamp-3">
            {{ post.content | safe }}
          </div>
        </div>
        <div class="bg-gray-500 max-w-[150px] ml-2">
          <img src="data:image/jpeg;base64, {{ post.image_base64 }}" alt="Image">
        </div>
      </a>
    </div>
  {% endfor %}
{% endblock %}

templates/posts/list_posts.html
{% extends "layout.html" %} 

{% block header %}
  <a href="/" class="flex hover:text-indigo-500 group transition duration-500">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-500 mr-2 group-hover:text-indigo-500 transition duration-500">
      <path stroke-linecap="round" stroke-linejoin="round" d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3" />
    </svg>
    Voltar
  </a>
{% endblock %}


{% block content %}
<div class="container mx-auto max-w-5xl p-6">

  <div class="px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
    {% for post in posts %}
      <a href="{{ url_for('postRoutes.post', slug=post['slug']) }}">
        <div class="flex items-center p-6 mb-4 rounded-lg bg-white drop-shadow-lg hover:border-indigo-500 hover:border">
          <div>
            <h1 class="text-2xl font-semibold">{{ post.title }}</h1>
            <p>{{ post.slug }}</p>
            <p class="font-light text-gray-400 py-4">{{ post.author }}</p>
            <div class="line-clamp-3">
              {{ post.content | safe }}
            </div>
          </div>
          <div class="bg-gray-500">
            <img src="data:image/jpeg;base64, {{ post.image_base64 }}" alt="Image">
          </div>
        </div>
      </a>
    {% endfor %}
  </div>

</div>
{% endblock %}

templates/posts/post.html
{% extends "layout.html" %} 

{% block header %}
  <a href="/" class="flex hover:text-indigo-500 group transition duration-500">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-500 mr-2 group-hover:text-indigo-500 transition duration-500">
      <path stroke-linecap="round" stroke-linejoin="round" d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3" />
    </svg>
    Voltar
  </a>
{% endblock %}


{% block content %}
<div class="container mx-auto max-w-5xl p-6">
  <div class="bg-white rounded-xl p-12">
    <h1 class="font-semibold text-5xl text-center pt-12">{{ post.title }}</h1>
    <p class="text-xs text-gray-400 text-center uppercase pt-5 pb-14">{{ post.author }}</p>
    <img class="mx-auto max-h-[580px] pb-14" src="data:image/jpeg;base64, {{ post.image_base64 }}" alt="Image">
    <div class="max-w-3xl mx-auto">{{ post.content | safe }}</div>
  </div>
</div>
{% endblock %}

templates/posts/view.html
{% extends "layout.html" %} 

{% block header %} 
  <a href="/solutions/list" class="flex items-center">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-green-700 hover:text-green-300 transition duration-500">
      <path stroke-linecap="round" stroke-linejoin="round" d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3" />
    </svg>           
    <span class="sr-only">Voltar</span>
  </a> 
  <a href="{{ url_for('postRoutes.edit_solution', solution_id=post._id) }}" class="flex items-center">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-blue-700 hover:text-blue-300 transition duration-500">
      <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
    </svg>
    <span class="sr-only">Editar</span>
  </a>
  <a href="/solutions/delete/{{post._id}}" class="flex items-center">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-red-700 hover:text-red-300 transition duration-500">
      <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
    </svg>       
    <span class="sr-only">Excluir</span>
  </a>
{% endblock %}


{% block content %}
<div class="container mx-auto max-w-5xl">
  <div class="bg-white rounded-xl p-6">
    <h1 class="font-semibold text-5xl text-center pt-8">{{ post.title }}</h1>
    <p class="text-xs text-gray-400 text-center uppercase pt-5 pb-14">{{ post.author }}</p>
    <img class="mx-auto max-h-[580px] pb-10" src="data:image/jpeg;base64, {{ post.image_base64 }}" alt="Image">
    <div class="max-w-3xl mx-auto">{{ post.content | safe }}</div>
  </div>
</div>
{% endblock %}